font=MesloLGL Nerd Font Mono:size=12
use-bold=yes
; icons-enabled=yes
anchor=top-left
width=25
lines=25
x-margin=6
y-margin=6
horizontal-pad=8
minimal-lines=yes
include=~/.config/fuzzel/colors.ini

[border]
width=2
radius=8
