-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀

-- ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

-- Example windowrule

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

hl.window_rule({
	match = {
		title = "^(Open File|Select a File|Open Folder|Save As|Library|File Upload|Rename|File Operation Progress)(.*)$|^(.*)wants to (save|open)(.*)$",
	},
	float = true,
})

hl.window_rule({
	match = { title = "^(打开文件|打开文件夹|另存为|重命名|文件操作进度)(.*)$" },
	float = true,
})

hl.window_rule({ match = { title = "^(Choose wallpaper)(.*)$" }, float = true })

hl.window_rule({
	match = { class = "^(pavucontrol|org\\.pulseaudio\\.pavucontrol|nm-connection-editor|Zotero)$" },
	float = true,
})

hl.window_rule({
	match = { class = "^(floating_shell|waypaper|QQ|org.kde.polkit-kde-authentication-agent-1|)$" },
	float = true,
})

hl.window_rule({ match = { title = "^(Open File|Open Folder)$" }, float = true })

hl.window_rule({
	match = {
		title = "^(打开文件|打开文件夹|从文件打开工作区|另存为|重命名|保存工作区|将文件夹添加到工作区)$",
	},
	float = true,
})

hl.window_rule({ match = { class = "^(steam_app).*" }, immediate = true })
