cursor #eddeec
cursor_text_color #d0c2d0

foreground            #eddeec
background            #18111a
selection_foreground  #432740
selection_background  #e3badb
url_color             #edb1ff

color0   #18111a
color1   #ff7287
color2   #7fffa0
color3   #ffdc72
color4   #dd99f2
color5   #663376
color6   #edb1ff
color7   #fbefff
color8   #a299a5
color9   #ff9fad
color10  #a5ffbc
color11  #ffe9a5
color12  #efbcff
color13  #f2c8ff
color14  #f6dbff
color15  #fdf8ff
