cursor #211922
cursor_text_color #4d444e

foreground            #211922
background            #fff7fb
selection_foreground  #ffffff
selection_background  #e3badb
url_color             #9a00cc

color0   #18111a
color1   #c1001c
color2   #009927
color3   #f4b900
color4   #a100d6
color5   #ebadff
color6   #9a00cc
color7   #383439
color8   #aba4ad
color9   #f40024
color10  #00e039
color11  #ffc000
color12  #b40aed
color13  #ebadff
color14  #df7fff
color15  #fcf4ff
